### ISSUE TITLE
when segment big pcd file(larger then 500MB),then Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by byronsit** [CloudCompare/CloudCompare#854]
gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3) 
ubuntu 18.04
GTX 760*2 
Qt: 5

I find this problem in many different computers.(like intel NUC or other my friends' laptop)
when i chose a big pcd file(for example: larger than 500MB), do many operators like transform or segment even just try to save the pcd, the cloudcompare will shutdown.

here is some informations:

Thread 1 "CloudCompare" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) 
(gdb) bt
#0  0x00007ffff1cb5e97 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff1cb7801 in __GI_abort () at abort.c:79
#2  0x00007ffff2c72fa7 in  () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#3  0x00007ffff2c8217d in QThread::~QThread() ()
    at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007ffff5ac4890 in ccPointCloudLODThread::~ccPointCloudLODThread() ()
    at /usr/local/lib/cloudcompare/libQCC_DB_LIB.so
#5  0x00007ffff5ac48ac in ccPointCloudLODThread::~ccPointCloudLODThread() ()
    at /usr/local/lib/cloudcompare/libQCC_DB_LIB.so
#6  0x00007ffff5ac3215 in ccPointCloudLOD::clear() ()
    at /usr/local/lib/cloudcompare/libQCC_DB_LIB.so
#7  0x00007ffff5aafc79 in ccPointCloud::clearLOD() ()
    at /usr/local/lib/cloudcompare/libQCC_DB_LIB.so
#8  0x00007ffff5a9b81a in ccPointCloud::notifyGeometryUpdate() ()
    at /usr/local/lib/cloudcompare/libQCC_DB_LIB.so
#9  0x00007ffff5aa0861 in ccPointCloud::invalidateBoundingBox() ()
    at /usr/local/lib/cloudcompare/libQCC_DB_LIB.so
#10 0x00007ffff5ab1be9 in ccPointCloud::refreshBB() ()
    at /usr/local/lib/cloudcompare/libQCC_DB_LIB.so
#11 0x00007ffff5aa242e in ccPointCloud::applyRigidTransformation(ccGLMatrix const&) () at /usr/local/lib/cloudcompare/libQCC_DB_LIB.so
---Type <return> to continue, or q <return> to quit---
 () at /usr/local/lib/cloudcompare/libQCC_DB_LIB.so
#13 0x00007ffff5a4cb40 in ccHObject::applyGLTransformation_recursive(ccGLMatrix const*) () at /usr/local/lib/cloudcompare/libQCC_DB_LIB.so
#14 0x00005555558e4191 in ccGraphicalTransformationTool::apply() ()
#15 0x0000555555a67e02 in ccGraphicalTransformationTool::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#16 0x00007ffff2e955b5 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007ffff3cd5b82 in QAbstractButton::clicked(bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007ffff3cd5d9a in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007ffff3cd717a in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007ffff3cd736d in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007ffff3db5fea in QToolButton::mouseReleaseEvent(QMouseEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007ffff3c23038 in QWidget::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007ffff3db6084 in QToolButton::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007ffff3be482c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#25 0x00007ffff3bec64f in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#26 0x00007ffff2e669a8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#27 0x00007ffff3beb622 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#28 0x00007ffff3c3e14b in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#29 0x00007ffff3c407ba in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#30 0x00007ffff3be482c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#31 0x00007ffff3bec0f4 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#32 0x00007ffff2e669a8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#33 0x00007ffff3428523 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#34 0x00007ffff3429ff5 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#35 0x00007ffff34012eb in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#36 0x00007fffebbb31c0 in  () at /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#37 0x00007fffeffa1287 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#38 0x00007fffeffa14c0 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#39 0x00007fffeffa154c in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#40 0x00007ffff2ebf8ef in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#41 0x00007ffff2e649ea in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#42 0x00007ffff2e6da84 in QCoreApplication::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#43 0x00005555559b24cb in main ()

**Comment by dgirardeau** [comment]
Can you send us the cloud file? (I don't have such large PCD files).

**Comment by comtm4** [comment]
https://drive.google.com/open?id=1Pafssw8kvuJ9oQm5GCKyuzE5RGIynUXg
can you download it...

**Comment by dgirardeau** [comment]
Done. I'll look at it asap.

**Comment by dgirardeau** [comment]
![image](https://user-images.githubusercontent.com/2735509/53443775-b90a7680-3a0c-11e9-88ec-3d2e89f36233.png)

Okay I could load it without any issue (with the 2.10.2 version on Windows). There's a peak of memory at 6.6Gb during the loading time (because the cloud is first loaded by PCL and then 'copied' to a CloudCompare structure. Then the memory usage is only 2.2Gb after this process.

Otherwise, can you also try to disable the 'load clouds on the GPU' option in the Display options? Just in case it's the cause of the crash (and not the lack of memory).

**Comment by comtm4** [comment]
it doesn't work...

loading it's ok, when try to use the tool of segment, and use 'segment in'... then Segmentation fault (core dumped)

when i use a intel NUC(without GPU) on ubuntu 16.04, it still have the same problems with the segment tool.

**Comment by dgirardeau** [comment]
Reading again your traces, apparently the issue is with the LOD thread.

Can you try those "solutions":
1) disable the 'Decimate clouds over' option in the display tool
2) or wait long enough so that the LOD structure has been fully generated (see that in the Console)

**Comment by comtm4** [comment]
> Reading again your traces, apparently the issue is with the LOD thread.
> 
> Can you try those "solutions":
> 
> 1. disable the 'Decimate clouds over' option in the display tool
> 2. or wait long enough so that the LOD structure has been fully generated (see that in the Console)

thank you! those "solutions" work!

**Comment by dgirardeau** [comment]
Which one did work? (well, anyway this means that there's a bug on Linux with the LOD thread :|

**Comment by comtm4** [comment]
> Which one did work? (well, anyway this means that there's a bug on Linux with the LOD thread :|

Both work all did work. thank you for your help.
